; generated by PrusaSlicer 2.5.0+win64 on 2022-12-22 at 16:35:04 UTC


;
; thumbnail begin 160x120 12908
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAlmElEQVR4AeWdaZsVxdmAzx+JGy5xz2
; YSFQEXNgGHWYCBgdln2FdRQVBUVGRRUEAEjKCgEnADFEUhvmpijJrlMm+MGkPMHq/8Aj/V23fBc6zp
; qe6u6q4+M/h+eC50Zs7p7qq7nr2qK3V1dQppampSd911l5o3b56Sn02cODFT6uvrnaShoUEtXbpUrV
; mzRk2ZMkX/f5I0NjZq6ezsVA888IBqb2+v/ixJuH9fmTx5srr11lvVggUL1KRJkzJl5cqV6sSJE+r9
; 999XN998s/68y+d8pKOjQ23cuFHNnj3b6e97enrUnXfeqebMmeN8Dd9xWrhwoVq/fr2aPn16n5/b5o
; G5veWWW9Rtt92mpk2b1u/38bmuCGwiTMaqVav0jYYCr7m5WYPEpGVBFxcmmQHmoUJAJ9LW1qa/l399
; ATl69Kj65z//qTZv3qwnJRR8y5YtU2vXrtUT5/O5lpYWPeHI1KlTva+bNEbAdN9996nly5dnjmd8bm
; bOnKnuuOMO1d3dbZ1XK4ACFwNw7733qq6urkLgIazkDRs26InyAS8uc+fO1YPBYOeFTgZ88eLFWhsX
; 0WAPPvighvDYsWOp2odrZAljg4ZhkcV/53o//C33gfJg0vM+lwCJZt20aZO2Qj5jbM4Zc3X77bfr8Q
; Zm27xWkswtELGioB9QXOETsLiZu+++W5stm+p1Bc/UdDwQEM6fP98LOBEmmvthcItMkDnhH3zwgfr8
; 88/1gmXhugBnCs/y0EMPaTfD97M2UNHoK1asUEuWLNGTnue5sAz33HOP/nzexW7OHc/IPdlcqUqWj4
; fJuf/++/XkuYCHcCH8GDRoCPDigvbCX7UNUNLAokFZTD4mymXi+b7du3er//znP+rAgQP6mV0+h1vC
; YmKyeY4i8NnuCb+N725tbXV+XuBlMRAHTPIw1S4g8t2YZPluJwAFLj7Aw6BK08BD8GNWr16tPxMaPF
; OAHH8py9ww0dxT0qD6ApckBDOfffaZ+t3vfqevx3WT/hYN/Mgjj2g/KSR4cWFsmDc0UJZJx/yvW7dO
; W5msccoLItcnDkARcJ1UAG1aDi0CXAxuHDzMDw/Aw+YBz/eBGAg0BwOMn2EbXPwXVt2MGTOCwpYkrP
; KDBw9qbbhz506tfeJ/gwuARUFLlQmfCBMNXIwR/23+jnFg3ggQWUCumrIoiCxA5qW3t7c/gFk+ngQo
; s2bNqkJG5Ax8/K4W4MWFe2EQxdwwuJjpeKqkFhOOkGr6+9//rt5++21tClkoYt7EIU+T0PfDdzJGuC
; 2m1sWHxVXCzUrTjqFhZN5ZgFiKig98pmZjxaANgZFgpUzwXAYA+HGceShWF9qvTMiyIGKi33nnHfXX
; v/5VPf744+rhhx/WEGZ9zkd875kFiiZk7pg3gsSk76kFiEjFFzwRnO1t27bpXJhLorgs8EzB/JMewc
; TFzU1ZoCHdUxutMru1WR0/9Jz68sQn6sW9T6hFPW2Jf2uTMsDE7BE0MU6i+dKkbAgrvvABEX4Mq0cg
; QeOwqgYKPLQfYT4mhUFD02CSyUGGhk2ktXmS2t55vXpr9o9Kk9dnXak2tI/W1wqhKXH+CdxYnCgQ/O
; dFixY5adPQIHJNLEPFR+uRiiGpzMTGzS0/E81TK/BkRbMguLc4TEDJICdFpHkndFXruFLBs4G4bMaE
; 3PeL6WXe8ItN2Fi4+MmMH4Ga60ItCiLuyXvvvac+/fRTO4A2+LhRtAqTmaTlcCzxLQhKygJPBoH7QO
; uygrNMDlUGfMIQflfZWi9NNneM9NaGBEGS6E76G4CggiIWpAwQZa4JVgnQDh8+rF2AShZ43CBRHavH
; NcgAVkw0kIQGD2EwGTCX6gH3LwEKwOYFb+60evXyzKsHDD6R53uvUXNb6jPvl2fGIuEeuTwfGhATTR
; DnW9FxmT/m6pVXXtHwwZOwUUmDj5WBs8rN+QYY4oeR8wkFHoLGA6S0RG/SIPNZHh6T5AMffthAgxc3
; yfe33ajHALFpNIJD/vV5Tr6LXC/pGpLYoSAk8qZcSVZA6uZ9gpA4ePyCm8B/KhLZciH8C3wxX5Udf0
; Cp4yZVD1wHGfhYGLgJSZMgMq+lQWucwQSfKc/2DFc905r63DNzhuZDi/nAZwqmEc1JPTltoWeBiEu2
; Z88e9a9//Uvt2LGjX5VFAxiHTxKmaK5QaRX8MCY9q/Up6aFYNUBsS63kHWRMDWaZiTInUAQNM1jBi2
; vDVa3jNTTMG1o+/ix5xodxIWkuLWu+EFL6pCz50UcfVYMf25xX4sllCuR8SQjw4quBxDX+oSt8ki1H
; W4WALq7lWGREhywQ+Vnb1Mlqd/e1pwV8phxeOUP1ts+wLqYiMDJG+NvkWPn/LPj4G+rcaL3nnnsuU+
; loAJloohNWj0ug4QufKawq6etL03qSpzJXX1HgbMJKJ2BCw948Y6LWKKcTeKbgLiyZPjETQl8YcX+o
; dtnqyfE5O378uPriiy+0dXHpPKrgdJKmiOfvQoNnCn4YwYAt7OeB0ZIU0GXFlQFeXHbNrz+tYEsSCV
; DQ5CFB5O+YL6knx7UhwAEeANr89EQACb1D+Xq+wQUrCvUuji5gSht3XvB8oJNAYzCkV0KLLUAJAaI0
; vKIg0HBkSOiDxORu2bIlVUMmmuCi8PmCZwqwYf7x9QAyT/TmC93pFmgU1Ya+45I13oCHX07Q8/HHH6
; tf//rX1S4fnyhZA1hrrRcXgCO9QlsQENYCPMwTGiLEJB+f+cNBC6CpDX1MchaIAEi/I32Pb775pvYP
; XeCzQVghAqy11hORxkRJDLOqXBLFecFD7mobH2RSX2r/nlp27RC1dty31cud3x+08JnacPmMm3KNmT
; n29BW+++67OrEsc4c5zltP1j4gH+Z/agUfD0XKRzbOmCKJYunSCAEeKxbZ0XVDkMnc0XSJmvnjM7Ss
; vOFcddeo89SeqZcPWvhM2dw5Mrc2pJOGUtqRI0e08jDnRRpefTqQqiaY8FkSxUXhy7qo1HGzmgNQ60
; RWOLVFwZs3vTFIoPFG7xVq9ejzq/AJgCIPTrhQvdZ9xaCFT4R0DcGX6ziS5KZ54B//+IcuzTIntjmT
; hlfZlO4CYdUH5AsgmKx1WSaXzgzZPO3i47EwSBER1vtCJ/Jgx5ggk4bJnX/1WX3giwMo2vDAjO+WAs
; 7eSMturb9YbZjw7cj0X6A21V2odkba+HCHvwugA5T27AAFC/mnP/1J/fKXv9QuUtbc8XuS1rDkskOw
; Eje5XIREMQSHgk/quKhnF/DMAeA+eBj8DR7OFTy0Xqg67kORZouDlwSgCGY6VICya8qlatE1Z6meH3
; 1Lzb7yDDV/6Jn6/28efra6ZcTZ6vbrh6h147+dS/sSoPS29E/XMGdPPfWU+ve//6127dqltVuzQ4Ai
; IvXkrOi4YtN2XJyCNknqoloP6KRh1Bc+U7gX0jU8WBp4CCs7xMRLoJEEXxqASIgAZeNNwP8t1R3Blw
; TgrSPOUcuvG6LuHn2eeqUznzZc3vp1gIIGI7VCigUNmFQvzwKRz+Hny/5kZwBF62Eu8df4sjyBBp+3
; BRM+4JlClMXCkCRoXNqmTSkl0MgLoBmg5NGGLACAcwXwjuh6GyOznPeZt3SOUls2rtdJZbaXkqN1mZ
; esuSXTAkcoES8AEYIFNA/23BU+PiMNoyHAi2s8AAREVlUtAo24MNFbJl6k9ke+Hv4egKHt0kDME6Cg
; /XwBXDXqXHW0J38g9OG909W2++/QFstnXrLmGeUhR72YAUrFJeDgCwCKRHGWyUXlSsNoSPji2k4WBq
; tqc7RyQ2i9p6ddnqnxdk25zPrZuyNNJxovTRs+2/Id5/u5d8z5uQBEcxYZBwlQsCghIRRXCp+eNI4V
; wDR/jw9LojgOHoTLbvcywTNl/oxGdWRhGPjW3niBF3wPRH8/56ozIh/xHLUkAmFDFATwc7Rhlll+tO
; FiJ5OMG+AL4Oox5wULfpIClCIQIlhG4gKaTiqu8JkRLVGyuRmI5kNp1akVfCEDjSXDznby9450/aCq
; KXsjKAAQCBYMPSsC7yScTH6aFjQDlKx0De4AYPkAuHda2IQ42pDqUUgAJV0DQxUf+EwhX8gOOEiWZs
; VQ8KWBh1nY3X1dkMHFj3MBj0gY+CSiBdo4gIdP/Q5ogPCR6LtDBChc67ZIy7oASLomJHx9tHEU3LlW
; UFxY6OMD5kmzECGhCemIoAxTC60XqmHUJb0iAqTyuc31F6ntjZdoEJjsnZMu0f++2v2D6t/gt8l/A5
; eLNiRASUvXAPUTky9Vt0WgzRn9fdU97hrVO36YmjXuKrVo5CVqW2TSXzPuoSwhrxoawoovfHyQKBT7
; LRcjz4P/Z7twCPCQUIGGa3oFQOPO/Jobz9fw4cMd6+2rtahSLLvunEgbntnn54CVFSH71JPfiBbgC7
; 3DtAxEH6OZLywCIb/Hdav4wCfnKpOSiX8hWpCo1KzxhoAvZHrFJdBAqHzYvkMAxGdcHsFG5IvfNSv6
; DCYSXy0OIIKJBfwsCEUbDuYWL0qbaRUpFwAJWGlqpdZfcYWPEh1pmLRaIEEIfiEaMgR8Ieu4LoEGtd
; 6nU5x4E8Clke/Fv/hjWQCa93Hf2POdtGFZ9eRQAOaFkLo+mRSxoJUs+IDKPPjHxbbz5ZIozgNeb8uk
; mtRx48lltGTadxUFEEG7YcJdtGHIevJAASgQknxGMQGfaSVTAYRW8+AfF/jkonKELnbeB77QDaMu8D
; HRLt+5Owo4AJDvTQJw3bgLnL6LhLRrumYwNbyaALpCCHBYRqmCmLxUbPDxIanjmsGHK3ymoD3Z9igF
; 7TT4al3HlfSK6/eKNlodRbo2ANc6wicCWPh8IdI1AwVgVocSDKGIkjqhKnH46DaxHfyTBz4RqiM0Mv
; Jv2YFGVh03K9BwkRfavqf78NZH1Y81UWBDzXb/jO/k+i4JUFzTNQPd8OoKIAErHFF2I+hI4qZiwkfv
; lu3gnyLwieBLEvVQMSkjvUJjgK1h1BZo7B+EDr5PgOJTT64FgHEIiRfosIenrKi4YjaM2jYUh4DPvF
; FRyUu7ptU80CANExqakNGqT4DiWk8OLdvnn+wXtQHIz/HzCEDjfZuJAEKr7MctG75qemVmmFMIfOq4
; SV0seUXKeGik0NEqUIeqJ4eW/923UW9Ep5vFnFP+H/DkfMFmh5SMBtB8iUnZ8IWs45YVaLhAb0bXZU
; Wr+Hqh6skhZd/KLr0l87e//a1WXPh3pN2wai57d6wmuAwAy6rjEmiQs/Ot45YFvQ2GUNcDKmrAgylA
; wQckrcJpp2xMp3OangBAdFFKTgCGhi9UoIEZddV6RZsy49AnlfFqAQPPErKeXBRATCz53Z/+9Kf6ja
; FvvfWW9u1d8oL9AOSLyjK9odIrSNE6bpHJT/Mza1VOGyz15Ed6J+jGE7QegQYxBCcl8EIettC6aMI+
; AOI0kquR1Eso+GrdMEp6JXSg4RJd17qcNtD15GdXdOpUHVpQ5poUG+/8+PLLL9WhQ4cyfcF+Jlg2gJ
; vHLeQ1vQQaoQ7+yWoYnXXlGTohHDLIkEl2LePdPirbNJZRTgNqAMsyzaEXwNr2MYmVLJqU2cr5hz/8
; QXdNuUTDVR9Q12EjTUgepwh8oXJ7WYEGgKy4foiuQjDAz7V+Vx3qKD7JrtF1z/CL9Ds7upob1JLxPy
; w9WqXfcF+UgMYffT56VulHdMkdAmkoAOfWDU8tp1IBef7557U2fPLJJzPzgZW474dPKOfE+JpemhVD
; PShaKKmshrmVwQeY+VefqWuytKdzdEWe6/mU8brGXKUtBt0d+DxtLVPVgrprnLRh3gCFZ109+jxFw8
; PiYWfpxScVEX6XZJaBL1RAtGrkuap97NUqq3kYHmg+wC/kSA/SNGaA0g/AuLaTDeByelWt/T4TCvyw
; eInN7F6hHmsCuPKGId5ahh5AlzJe71XnqLamCXp8pKmS9iLq5vx/z5Q6tWz0xU7a0Lecxliw90MAZJ
; /IuvFfV3Zs6RrXLh8XZYAfjsvjCiCCS/ezn/1MH2rE20KlPS8TQBF5rWfaJmXzwqEBFKF2qztPTjWM
; svFaIHux7Xt6QgRA9sXKBiEXJ9y1jNc16odV8EyhE5zDNbEcpjZ0iVZdymlmOml748VqXrTYBEC9NS
; D6PHDiB0uAAoih0lCmH+4LoPDB0b3kDF977TUdNfcBMCvtIhvAaacZKABFA0jDKA79Y41fTx4/Pxj5
; f/hFz7Rcrs9IeWDcBantUT5lvI66kVb4RFjZvIKCtjP+W7Sha4CStlAen3SJ2jf9a215LHpWfF2efU
; v9RZGvfHI7pnxHqIDDFojlAVCEk9F4b8hnn31WfT9LJoAmZLTWENmYF4hfeE17bd4iCYBoOjaHy/Fk
; wPdqpAXYF8teDfr1kgB03Y4pgUYafKawbUHazkQbFg1QAPDOyPfC1aANjB14PCsaj+dA69OFHTLlkh
; SIFQEQwZI+/fTTOkDZt2+fzr44ASiCFpRzYuIAYu/33jmrJgAyUWyR5Fgy/KKlw89Wi685S82NzBMd
; y0yIDUAmzTW90nnjNc7gmULUR12UbIL8bG7DDbkDFAFw2XVDNGzsBV4YPevsq87Qz8pzEhxkbSdwka
; xADAA7xg7NDaAInVd//vOf1YcffpgMYBrFZMHxD+WCfCFgru8OFwW7yJPNl2kIXQB0LeOh9dom1+eC
; zxQS/ICIC8PCPfTsk+qh9lHO2tAVwFCBhks/ZSgAxbV79dVX/QEUIelIKmLTpk1VGMv0AZME83tP5P
; PZANxaf5HXAJNeKQqeKZhi6qWkI6iXLpw3Ry3MCFDiETIuhQ1AFl6oQMM1EAsJYGoQ4pJ2oduVd4Lx
; WlAczIECEMEnwh8SAO8bc77ewRavkCSZGNIr7fVjg8KHm8K70jhhlP45ya2mpWtsOTsifhaYCeDmQF
; 0+PhWfQQMgdT9yXwQlXIxohuI0kc0DnWF2tOUVHHFSFI/UpU/QyeT1SW3Yfe1lqrVlalD4sAiUpIj6
; 2NxFZEyahnQN5tgWoKR1sRB03R+lV9B6ewN1u7hWfEIGISaA/Mtpa14AyouQyX3FL8rvnlk1pyagpY
; mrM87qX1oX1uSi4X7yk5/onJd0DZu/J2FNgl/eqYGsmDzCuU4cPw4k7/i49lOWBSALEheOZuiKK3xo
; PDQfGjDpwgNlgnNPxqwr1dpIa3e1thSGDw33i1/8Qp04cULnBMXc2oTB5zWx62octLkGYmkAto0bXg
; hAFBVWgcOtrCY4/gHSCpgOeRFy2oVPNwBF9vWOULNbm3PDB0y8wOX111/XZiXTP4yA3zNzZE2f0bWf
; MlWuPke1TGrIBSCKi7iB8q55YH0qgBTbOX6N1dyckHz+JgCIoA3v6ajzAg8T+/LLL+tDvQnIWKyZ/m
; F7o75WrZ7Lp+KTmp4adqGa0VSXCZ8NQAIytB6uW2YQIrk+8npsOrFFwN9EAEV2do90Msk0IvACl/ff
; f1+bVCnBpcnW7jGqls/iWvHJko7RP9bBptmE6gIff4+fhyLD/43D1w9A/oBiMavZdkR/1sW/CQAiL8
; wcplZ22JPRDOSePXt0oLF37169urPAW9Q2Wb08c2jN7t83vZIkpKeWz+3SELnAZwLIOJENkM/aUjB9
; AOSXOM90vyR1smZdfEHj9YVeEeAjpCOoBZO45XjalVGKgtxf3ldXxcUWoOAH8wKXTz/9VNfF0wINkb
; U1Tk3lSa8kmdyW5snVNBuNFmkBqCmkmjC5UrJNygFWAeQPqWjYTrLyAXDOxOt00bzM05xY3eT6OAyo
; NxKSz1QG9JFpp85Mpllze6BWdAlQSD/h67EdUXJ5WYEGn60VeD4HcGZJ+7gRVZMrgv9Go0V8Q7opPD
; fNpwQbthY+W8pPv64Vf48PZ+VvXACkMF7W9kASzaQCek6dGp8EIL1yZrt+0ev+z4Lh6uMXt+vSozSf
; AhgBBYKJNeEjmKkVeLIoQwUa06NAIw6fmF+gwkrGz/dBABOtR5olKRK2Aihvu3YtwaUCWH8SwLTuji
; ICYD4AUkMN+dqCfb3XauBsmu3h6cM0fAQxtYTPtY7rE2gkASgi5/uwGDHLlGIJxMxsiTOAvjVgHwBD
; bg/ExPCKAl8AN9eHPR3B1DrsP9k1+VLdlTN/2JDTNtBorRudCp8tAAE+3DZq3ASuaS80TIJPA2i+z6
; 0MAENtD5QX9w0GAG3vCWFrQK3gCxVodI68IhM8G3z8jIQ7US47KQlcs14sngggLdJihssEMMT+WKJd
; XwDNdvaQACS9KalM8dm5lyVtN93gBF8cQPKd5PUww3JMG/4f1aC0DemJANIyRIv07t27MykuCmBW+3
; mW6N1rQ890BnD9+HD7YRGBmXaoxdH1eFsR7wYx26OenlbO2SyuB3BmBhrDo0BjSmMu+IiEabSNn3Qr
; SeekF4tPSem6rwAdHRrSIp2WinGNgl12hOUNUPafarnKAjDv/uA0AWj6Dck52n7PW5OyTsnPI8ECjb
; FDtZJBfABE05FakYrP1KnJ1Q/bi8VTAZT/ALzjx4/rXBfNB2UDaOv+9TFF7INdcePlakH9CDWrcbSa
; 3TRa3dV4pdradFlpr62S1zSw9ZGENxqR+2d3muzZDQlgsPTKcOq4E3PBR0UMFw2wbP6gjROyASg1gE
; 2Dr18UDN1bt27VEB49erRfOS40gD77YweDAMQi0baWU/LZIB/KBAcLNEZfWQXPBz7+ll1+wIc2s813
; VsyAr8j+IbP7xRT9rrh4GoYv5oMffPCB7m2jD7BsAF32xw4WQftuqruwH4CcyBBqZ1qo9AqBRh74pI
; 5Lfi+t/JYFIEzJLkHbaxqsAIpQnnvmmWeqezhRq1kA9jSOyQ1g0QCl1kItGl8TAEPtTCvaMPq1yb1I
; 3bdqpZ5DXwDJ6RFopJXcXOEzuaILXLZxCHypACLcNEXoTz75RH300UfaEU27KYrXt429LDeARQOUWg
; snFLwa6Gi4YHXc8SP0vInmwQ9zgQ/3izoukqVssuBLCjxI01DOZEumE4AiqM8jR47oFqRt27ZZnVGJ
; ltbce7da0TSsMIS1OG52MEhZgYYItX78MABLgo+0ClqPeU6a27zaLy58PxvYMPHOAEpkQ3RM6zl7XK
; XobOaIOIRGHmJ25A/ePvKCINrwdDDJeSRUw2g80IibXcwpnSxSMhNBYZBQBgb8vizwisJnml78SyJl
; 501JEoTQ08/mm7/97W/6C/iZbFiSzHjVmZ08Ud065rIg2vB0CFB8tF6wQGPimFT4zKiWRDEiJloaRl
; 37/PKaXhuACFrZC0CBEBu+a9cuHaC888471fcIm1JdZVOnqPk3DQ2iDQfj60t9JVR6pfvaS/XYusBn
; Cvnexx57TFcsCFJcTG4Z8Fl9QBcABUKgoyX997//vQ5SzLNiTABFOpvGOx3e6JKuGUyvL3WVkHVcCT
; R84aNdihQbQhcLOT4X+EKa3sIAyoYlNuVwY/iCL774otaGaEVTnccHgBW7cPyP/98FKKHruL7gIfjo
; BCT8Kz8TEG3ltbLh4/poYa+TEWTDUjxHpPc+RCH/X/7yF/WrX/1Kl21sAIrMbBgVLEAZ7OmaUHXctE
; AjDT7mhvQZsKEBzTKbuFMoFHzBWpleKmzEDARATgByI4TO5oYl280S2bz55pv67TlEXWkQEqAsHndF
; EG04kK8vTZJQ6RXdMNowPhd8TDSuEn6f+Xe2uSNRHN94FBo+/h9XjbQQ98argjMBTNqwlKSuCedxcj
; kVivPfuFDSAIUMUAZTPTlkw2ge8PgdGg34JNBIg08Ed4q+PixcaPjQvoCH38l98LNEAAXCrA1LSQ/C
; Bfjsb37zG93mha1P809CBigh3xHnK0UO/olLvI7rCp/UcTFvzJsLeKbIi8WZv1DwYRkxueSI5WfAlw
; ignHcCrS4RcZKwkjigkQCFs4HTsvGiDUMFKLXWhuHquPkDDXx0wKGy4ar1knw+oJEzDfPCx/3K2eIw
; FYfPCiCqm4qH7Q03vgAiRM34jrT+c14eKzNLG4YKUGqRruEQzFB13HmTxmg/jDHzAU/quNIwWhQ+Ee
; ADQjmYygc+om0+S0sXn7PB1wdAbgAbLS8udEnJuEKI4EPSY0g9mZ7DtEFFGy6d8KPCENIuz9uF6GSm
; 7LU5oGyIvvOOkefqPkAaUYtqPanjosXkpP0s8BCsDFqPz2UFGq7gxQVf0ny1Qhp84rqxf9hsOrDBVw
; WQh+BNNlDrmpLJAyErijQOb87hDTo4vbZBZeMzB/888+AqtcLhdPk0AOVYWxpJQwovjOk9tTelCIC2
; 9ApaDGXARCYu0khLYialYTSU1ksSeaElCyMJPu4DXw9NLIFGGnwaQHndVBrdoQCUAIUbfO+99/Th3Z
; LakZwVB/8QQbNJCoe6SD15MAOYVMc1QcKsygZw8+dMNOBh3gAxD3g+8JlWEgtJyiZujukRgCOUSjzv
; lwSfBpAkZZZdD6kFRVDPwEaAwtsVgZKDf/74xz/qKos5sHkDlMEKYLyOm+oTn0oU44fxtyT5pWG0bK
; 2XxAPmXhYGSgO/VebMBz4NoMtb0suCUKIkNN5XX32lGxviA1skXTMYAZQ6bpZvFxfG6dFHH9ULNU96
; JRR8IsCGL79z587q+9984WtqalIViVAGAkJge+ONN3SPIS1eaEPevG1qP1uA4lpBGUwA6oN/Jjd6g4
; fgd1FKwyRzYq3tkPhawsc9YYYJTPDXCThYVL7waQBRnTi9tYYQtU3tmOZWImTugdwjfuG7777br3ky
; Li4Nr4MFwKyDf9ICDUyvWcflZ0y8NIOEBM8FPipbpFfw+fhuqXLwMxaGD3waQJxGHEt5G2bZEAIayW
; nM7vbt2/t1YuCTvv322zpSxvdJm6CsAGWgASTQmFE/Lhd8RJ1mHTc+jgQgsgG8FuDxN1RYaELGcsXN
; LX/DoqDqxX+7wKcBlIw1qpQLJO3hzAuhCSKrhv5BEtKs6iQfhkHFtyBnyCHg8Xpm3CQn1ZMHEsDOkT
; /IBR5zAXRywmiaZhPNI28kLws+rkO2grRQ3NTGzS5wysLIgq8KoAhVEJxdviQkhAysNCjs379fR3Yu
; AQqLAljJCfLfqdGiJUAZKADbJlyfCz4mWuq4sr3BRYA168XiecBD0LRyBJst0LD5fHw3LhYBUxp8/Q
; AUe07tDlPIoBSFEBOPScXf8zlnWAQHXA5QIm1jRoA2bWg2vNYawJOBRkMu+KRhNH7wj6tIojjpxeK+
; 8DFPcIBCkhjBBT5TgJeEOt/lDKCUU1DrRDqo0rwQkphk8xIvcDGP7vIdXKDjuz7//HOdK+TB0iazp3
; GsNsm1BLB97FBv6Hg2tBauSdLBP1kSd3VsLxb31XrMlVkD9gXPFJ4Pv5H8ZRy+xsZGO4Bm5yoBCh/O
; unnzIUlQvvTSS7oxlRJfkmnwHWxchGPHjmlTzvfKz5O04ZzxV6ubrz2vVAA7rvuOuvOWRVWLkQWcKd
; IwKhF/XvDiIi8Wx9XxAY+/434w52jUPFovyeTiWrAwuI7Alwmg9O5zUwiayCVS4jUGvMCFFZQ1WL4g
; 4iKw/xi4ySHajpDoA2Jz5Nt2RbXVZYvVoq7pqr1xvGprHFdcGvpGt/ioTJy4CFn+LVqcsUqLYn2gi4
; t0IRHsucDHfaCpuCfuPyR8InJaAwvDGUARtCDqPakYzU2zKQnt9NRTT2UeWF0ERK7FwAL5F198oX1L
; 298xCTjomJO0CksRMa8nG8DTEsXSMAqAIffjJplbXCnASlMeaG9cHMnjFTG5SfCJ8DekapgXDSA/cI
; UQH4UP81AMnjwAJoTNSGg+SZDmHTQfEM0DlMgtmj4U5g0HWGqUrt9ZVOQ8HekCN3/nevBP0fGLAwb0
; aB6UiPlzxkXu1WwYLQs+0XoIsDM/FfmwK4Q8ICsGe45KZcWTND58+HD1FZw+UXJREBlE/FSaGMgxsj
; hoU2LAyafVCry4cG05iEde4EKwkXbwT5GxcvHzcBPkhCoWA5YBv7q5YKCRBV4cPhHuo2J+kSuEPAw3
; LvVbBtrUiD6RcigYcbxpeP3vf/+rDh065HzWSZmCRmZDV5pZLhs6W4TL9gjKniiQWmo9m1TiX+gCIG
; aNzUY///nP9SoiXcNgu0RZIcQ2kZgXBpU3ltPcQGdN3qJ9CGFBoonRemge8cNCjYEveAguC74e2hjT
; ix9Wa61nSkNDQ38A0yDEp+E4DgKNHTt2VMt2aB/MoO19sGWCiDCpJHAZWKmw4CKwOMhB8vNawycH/2
; CGGTPuU/r6MH21hE6EPGO8josVY3zE/3MBLxR8jBPjUUm7kAkfN0tZjIMqeZi43wCMaEafenJRGBlM
; BhXHXiZaBAieeOIJ7SIcPHjQK93hK6ZmRhOjWcwcnPl7HH4Wq4/5zQsd8wJc8n43Wx1XDhQnKq+V1h
; P/mDmrZF2Um5Q3RR44cED7Vmm+IQ+Co2sLSEKByI1j2gg00l6Owt+xKFg0ROgsjiLAZ2liFqZ0Lqf9
; LZaCCbC9zjQEdKbSyKrjyjwzNphlrl0WfHwPiwGLBYiJJliEAeLVDVLHZdW6+IhACoSyBdN3ENMmj+
; /mXojCXYvv5C5feOGFPgcohYRPThjlX9fPcA9Mhuy9LmJe43Ax5qJpyce6+nlYCcyiHJsRCjwElmS7
; r8CXCiBNjyR5KX0xsK4RspmuQSMQoJjvo8sLI/Cjus29pj4CrHyWk/9JYEt5sYgAEYtMzlX2/TzPJ0
; ngrCqTC3gIbklaHTfL4vGdwIvJDhHlIlghlAbfZ8KnATQz1AgThanF5LKFkon3jZLjA8JKFOc7zyCL
; f0lpKU+FxRTMEltC5QClvN+Dj4fZ4rlc/bmk55O+Pu4tD3Ti/nA/SXVc1wBDoMO1kYWRFzzmjcwEYx
; QHD6mvr1f/B53Of6/pDheKAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.45mm
; first layer extrusion width = 0.42mm

M73 P0 R24
M73 Q0 S24
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.11.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G0 Z0.2 F720 ; Move to z height
G1 E-0.8 F1800 ; Retract
G1 Z0.4 F720 ; Z hop
G0 X10.0 Y0.4356 F4800 ; Moving to line position
G1 Z0.2 F720 ; Z hop return
G1 E0.8 F1800 ; Un-retract
M204 S800
; printing line start id:0 copy 0 
G1 F2400
G1 X10.0 Y150.0 E9.32725 ; Create Line 
; stop printing line id:0 copy 0


;TYPE:Custom
; Filament-specific end gcode
G1 Z9 F720 ; Move print head up
G1 X0 Y200 F3600 ; park
G1 Z57 F720 ; Move print head further up
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 2246.67
; filament used [cm3] = 5.40
; filament used [g] = 6.70
; filament cost = 0.17
; total filament used [g] = 6.70
; total filament cost = 0.17
; estimated printing time (normal mode) = 24m 22s
; estimated printing time (silent mode) = 24m 31s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.6
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.3
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_solid_infill_speed = 40
; top_solid_layers = 4
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
