; ### Marlin K-Factor Calibration Pattern ###
; -------------------------------------------
; generated by PrusaSlicer 2.2.0
; Version: 1.2
;
; Created: Sat Sep 05 2020 12:57:57 GMT+0200 (Central European Summer Time)
;
; Settings Printer:
; Firmware: MK3S
; printer_model = MK3S
; filament_type = PETG
; Filament Diameter = 1.75 mm
; nozzle_diameter = 0.4
; Nozzle Temperature = 250 °C
; Bed Temperature = 85 °C
; Retraction Distance = 1.4 mm
; layer_height = 0.3
; total filament used [g] = 1
; estimated printing time (normal mode) = 2m 15s
; Extruder = 0 
; Extruder current = 538mA
; Fan Speed = 0 %
;
; Settings Print Bed:
; Bed Shape = Rect
; Bed Size X = 250 mm
; Bed Size Y = 210 mm
; Origin Bed Center = false
;
; Settings Speed:
; Printing Quality = DRAFT
; Slow Printing Speed = 1800 mm/m
; Fast Printing Speed = 3000 mm/m
; Movement Speed = 10800 mm/m
; Retract Speed = 2100 mm/m
; Unretract Speed = 2100 mm/m
; Printing Acceleration = 800 mm/s^2
; Jerk X-axis =  firmware default
; Jerk Y-axis =  firmware default
; Jerk Z-axis =  firmware default
; Jerk Extruder =  firmware default
;
; Settings Pattern:
; Linear Advance Version = 1.5
; Print Pattern = Standard
; Starting Value Factor = 0
; Ending Value Factor = 0.2
; Factor Stepping = 0.01
; Test Line Length Slow = 25 mm
; Test Line Length Fast = 100 mm
; Test Line Spacing = 4 mm
; Print Frame = true
; Print Size X = 168 mm
; Print Size Y = 105 mm
; Print Rotation = 0 degree
; Number Lines = true
;
; Settings Advance:
; Nozzle / Line Ratio = 1.25
; Lift-Z = 0.2 mm
; Z-axis Offset = 0 mm
; Bed leveling = G80 ; mesh bed leveling
; Use FWRETRACT = false
; Extrusion Multiplier = 0.95
; Prime Nozzle = true
; Prime Extrusion Multiplier = 2.5
; Prime Speed = 1800
; Dwell Time = 2 s
;
; prepare printing
;
;G21 ; Millimeter units
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.0 ; tell printer latest fw version
G90 ; Absolute XYZ
M83 ; Relative E
G28 W; home all without mesh bed leveling
T0 ; Switch to tool 0
G1 Z5 F100 ; Z raise
M104 S250 ; Set nozzle temperature (no wait)
M140 S85 ; set bed temp
M190 S85 ;  wait for bed temp
M109 S250 ; Wait for nozzle temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling; Activate bed leveling compensation
M204 P800 ; Acceleration
G92 E0 ; Reset extruder distance
M907 E538 ; set extruder motor current
M106 P0 S0
G1 X125 Y105 F10800 ; move to start
G1 Z0.3 F1800 ; Move to layer height
;
; prime nozzle
;
G1 X41 Y52.5 F10800 ; move to start
G1 X41 Y157.5 E16.3702 F1800 ; print line
G1 X41.75 Y157.5 F10800 ; move to start
G1 X41.75 Y52.5 E16.3702 F1800 ; print line
G1 E-1.4 F2100 ; retract
;
; print anchor frame
;
G1 X51 Y49.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X51 Y135.5 E5.6045 F1800 ; print line
G1 X51.5 Y135.5 F10800 ; move to start
G1 X51.5 Y49.5 E5.6045 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X201 Y49.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X201 Y135.5 E5.6045 F1800 ; print line
G1 X200.5 Y135.5 F10800 ; move to start
G1 X200.5 Y49.5 E5.6045 F1800 ; print line
G1 E-1.4 F2100 ; retract
;
; start the Test pattern
;
G4 P2000 ; Pause (dwell) for 2 seconds
G1 X51 Y52.5 F10800 ; move to start
M900 K0 ; set K-factor
M117 K0 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y52.5 E1.4811 F1800 ; print line
G1 X176 Y52.5 E5.9245 F3000 ; print line
G1 X201 Y52.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y56.5 F10800 ; move to start
M900 K0.01 ; set K-factor
M117 K0.01 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y56.5 E1.4811 F1800 ; print line
G1 X176 Y56.5 E5.9245 F3000 ; print line
G1 X201 Y56.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y60.5 F10800 ; move to start
M900 K0.02 ; set K-factor
M117 K0.02 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y60.5 E1.4811 F1800 ; print line
G1 X176 Y60.5 E5.9245 F3000 ; print line
G1 X201 Y60.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y64.5 F10800 ; move to start
M900 K0.03 ; set K-factor
M117 K0.03 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y64.5 E1.4811 F1800 ; print line
G1 X176 Y64.5 E5.9245 F3000 ; print line
G1 X201 Y64.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y68.5 F10800 ; move to start
M900 K0.04 ; set K-factor
M117 K0.04 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y68.5 E1.4811 F1800 ; print line
G1 X176 Y68.5 E5.9245 F3000 ; print line
G1 X201 Y68.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y72.5 F10800 ; move to start
M900 K0.05 ; set K-factor
M117 K0.05 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y72.5 E1.4811 F1800 ; print line
G1 X176 Y72.5 E5.9245 F3000 ; print line
G1 X201 Y72.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y76.5 F10800 ; move to start
M900 K0.06 ; set K-factor
M117 K0.06 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y76.5 E1.4811 F1800 ; print line
G1 X176 Y76.5 E5.9245 F3000 ; print line
G1 X201 Y76.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y80.5 F10800 ; move to start
M900 K0.07 ; set K-factor
M117 K0.07 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y80.5 E1.4811 F1800 ; print line
G1 X176 Y80.5 E5.9245 F3000 ; print line
G1 X201 Y80.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y84.5 F10800 ; move to start
M900 K0.08 ; set K-factor
M117 K0.08 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y84.5 E1.4811 F1800 ; print line
G1 X176 Y84.5 E5.9245 F3000 ; print line
G1 X201 Y84.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y88.5 F10800 ; move to start
M900 K0.09 ; set K-factor
M117 K0.09 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y88.5 E1.4811 F1800 ; print line
G1 X176 Y88.5 E5.9245 F3000 ; print line
G1 X201 Y88.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y92.5 F10800 ; move to start
M900 K0.1 ; set K-factor
M117 K0.1 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y92.5 E1.4811 F1800 ; print line
G1 X176 Y92.5 E5.9245 F3000 ; print line
G1 X201 Y92.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y96.5 F10800 ; move to start
M900 K0.11 ; set K-factor
M117 K0.11 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y96.5 E1.4811 F1800 ; print line
G1 X176 Y96.5 E5.9245 F3000 ; print line
G1 X201 Y96.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y100.5 F10800 ; move to start
M900 K0.12 ; set K-factor
M117 K0.12 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y100.5 E1.4811 F1800 ; print line
G1 X176 Y100.5 E5.9245 F3000 ; print line
G1 X201 Y100.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y104.5 F10800 ; move to start
M900 K0.13 ; set K-factor
M117 K0.13 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y104.5 E1.4811 F1800 ; print line
G1 X176 Y104.5 E5.9245 F3000 ; print line
G1 X201 Y104.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y108.5 F10800 ; move to start
M900 K0.14 ; set K-factor
M117 K0.14 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y108.5 E1.4811 F1800 ; print line
G1 X176 Y108.5 E5.9245 F3000 ; print line
G1 X201 Y108.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y112.5 F10800 ; move to start
M900 K0.15 ; set K-factor
M117 K0.15 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y112.5 E1.4811 F1800 ; print line
G1 X176 Y112.5 E5.9245 F3000 ; print line
G1 X201 Y112.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y116.5 F10800 ; move to start
M900 K0.16 ; set K-factor
M117 K0.16 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y116.5 E1.4811 F1800 ; print line
G1 X176 Y116.5 E5.9245 F3000 ; print line
G1 X201 Y116.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y120.5 F10800 ; move to start
M900 K0.17 ; set K-factor
M117 K0.17 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y120.5 E1.4811 F1800 ; print line
G1 X176 Y120.5 E5.9245 F3000 ; print line
G1 X201 Y120.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y124.5 F10800 ; move to start
M900 K0.18 ; set K-factor
M117 K0.18 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y124.5 E1.4811 F1800 ; print line
G1 X176 Y124.5 E5.9245 F3000 ; print line
G1 X201 Y124.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y128.5 F10800 ; move to start
M900 K0.19 ; set K-factor
M117 K0.19 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y128.5 E1.4811 F1800 ; print line
G1 X176 Y128.5 E5.9245 F3000 ; print line
G1 X201 Y128.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y132.5 F10800 ; move to start
M900 K0.2 ; set K-factor
M117 K0.2 ; 
G1 E1.4 F2100 ; un-retract
G1 X76 Y132.5 E1.4811 F1800 ; print line
G1 X176 Y132.5 E5.9245 F3000 ; print line
G1 X201 Y132.5 E1.4811 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X51 Y136.5 F10800 ; move to start
;
; Mark the test area for reference
M117 K0
M900 K0 ; Set K-factor 0
G1 X76 Y137.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X76 Y157.5 E1.1849 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 X176 Y137.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X176 Y157.5 E1.1849 F1800 ; print line
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
;
; print K-values
;
G1 X203 Y50.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y50.5 E0.1185 F1800 ; 0
G1 X205 Y52.5 E0.1185 F1800 ; 0
G1 X205 Y54.5 E0.1185 F1800 ; 0
G1 X203 Y54.5 E0.1185 F1800 ; 0
G1 X203 Y52.5 E0.1185 F1800 ; 0
G1 X203 Y50.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y58.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y58.5 E0.1185 F1800 ; 0
G1 X205 Y60.5 E0.1185 F1800 ; 0
G1 X205 Y62.5 E0.1185 F1800 ; 0
G1 X203 Y62.5 E0.1185 F1800 ; 0
G1 X203 Y60.5 E0.1185 F1800 ; 0
G1 X203 Y58.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y58.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y58.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y58.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X209 Y58.5 E0.1185 F1800 ; 0
G1 X209 Y60.5 E0.1185 F1800 ; 0
G1 X209 Y62.5 E0.1185 F1800 ; 0
G1 X207 Y62.5 E0.1185 F1800 ; 0
G1 X207 Y60.5 E0.1185 F1800 ; 0
G1 X207 Y58.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X210 Y58.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X210 Y60.5 F10800 ; move to start
G1 X210 Y62.5 F10800 ; move to start
G1 X212 Y62.5 E0.1185 F1800 ; 2
G1 X212 Y60.5 E0.1185 F1800 ; 2
G1 X210 Y60.5 E0.1185 F1800 ; 2
G1 X210 Y58.5 E0.1185 F1800 ; 2
G1 X212 Y58.5 E0.1185 F1800 ; 2
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y66.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y66.5 E0.1185 F1800 ; 0
G1 X205 Y68.5 E0.1185 F1800 ; 0
G1 X205 Y70.5 E0.1185 F1800 ; 0
G1 X203 Y70.5 E0.1185 F1800 ; 0
G1 X203 Y68.5 E0.1185 F1800 ; 0
G1 X203 Y66.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y66.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y66.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y66.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X209 Y66.5 E0.1185 F1800 ; 0
G1 X209 Y68.5 E0.1185 F1800 ; 0
G1 X209 Y70.5 E0.1185 F1800 ; 0
G1 X207 Y70.5 E0.1185 F1800 ; 0
G1 X207 Y68.5 E0.1185 F1800 ; 0
G1 X207 Y66.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X210 Y66.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X210 Y68.5 F10800 ; move to start
G1 X210 Y70.5 F10800 ; move to start
G1 X210 Y68.5 E0.1185 F1800 ; 4
G1 X212 Y68.5 E0.1185 F1800 ; 4
G1 X212 Y70.5 F10800 ; move to start
G1 X212 Y68.5 E0.1185 F1800 ; 4
G1 X212 Y66.5 E0.1185 F1800 ; 4
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y74.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y74.5 E0.1185 F1800 ; 0
G1 X205 Y76.5 E0.1185 F1800 ; 0
G1 X205 Y78.5 E0.1185 F1800 ; 0
G1 X203 Y78.5 E0.1185 F1800 ; 0
G1 X203 Y76.5 E0.1185 F1800 ; 0
G1 X203 Y74.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y74.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y74.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y74.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X209 Y74.5 E0.1185 F1800 ; 0
G1 X209 Y76.5 E0.1185 F1800 ; 0
G1 X209 Y78.5 E0.1185 F1800 ; 0
G1 X207 Y78.5 E0.1185 F1800 ; 0
G1 X207 Y76.5 E0.1185 F1800 ; 0
G1 X207 Y74.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X210 Y74.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X210 Y76.5 F10800 ; move to start
G1 X212 Y76.5 E0.1185 F1800 ; 6
G1 X212 Y74.5 E0.1185 F1800 ; 6
G1 X210 Y74.5 E0.1185 F1800 ; 6
G1 X210 Y76.5 E0.1185 F1800 ; 6
G1 X210 Y78.5 E0.1185 F1800 ; 6
G1 X212 Y78.5 E0.1185 F1800 ; 6
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y82.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y82.5 E0.1185 F1800 ; 0
G1 X205 Y84.5 E0.1185 F1800 ; 0
G1 X205 Y86.5 E0.1185 F1800 ; 0
G1 X203 Y86.5 E0.1185 F1800 ; 0
G1 X203 Y84.5 E0.1185 F1800 ; 0
G1 X203 Y82.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y82.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y82.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y82.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X209 Y82.5 E0.1185 F1800 ; 0
G1 X209 Y84.5 E0.1185 F1800 ; 0
G1 X209 Y86.5 E0.1185 F1800 ; 0
G1 X207 Y86.5 E0.1185 F1800 ; 0
G1 X207 Y84.5 E0.1185 F1800 ; 0
G1 X207 Y82.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X210 Y82.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X210 Y84.5 F10800 ; move to start
G1 X212 Y84.5 E0.1185 F1800 ; 8
G1 X212 Y82.5 E0.1185 F1800 ; 8
G1 X210 Y82.5 E0.1185 F1800 ; 8
G1 X210 Y84.5 E0.1185 F1800 ; 8
G1 X210 Y86.5 E0.1185 F1800 ; 8
G1 X212 Y86.5 E0.1185 F1800 ; 8
G1 X212 Y84.5 E0.1185 F1800 ; 8
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y90.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y90.5 E0.1185 F1800 ; 0
G1 X205 Y92.5 E0.1185 F1800 ; 0
G1 X205 Y94.5 E0.1185 F1800 ; 0
G1 X203 Y94.5 E0.1185 F1800 ; 0
G1 X203 Y92.5 E0.1185 F1800 ; 0
G1 X203 Y90.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y90.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y90.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y90.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y92.5 E0.1185 F1800 ; 1
G1 X207 Y94.5 E0.1185 F1800 ; 1
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y98.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y98.5 E0.1185 F1800 ; 0
G1 X205 Y100.5 E0.1185 F1800 ; 0
G1 X205 Y102.5 E0.1185 F1800 ; 0
G1 X203 Y102.5 E0.1185 F1800 ; 0
G1 X203 Y100.5 E0.1185 F1800 ; 0
G1 X203 Y98.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y98.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y98.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y98.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y100.5 E0.1185 F1800 ; 1
G1 X207 Y102.5 E0.1185 F1800 ; 1
G1 E-1.4 F2100 ; retract
G1 X208 Y98.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X208 Y100.5 F10800 ; move to start
G1 X208 Y102.5 F10800 ; move to start
G1 X210 Y102.5 E0.1185 F1800 ; 2
G1 X210 Y100.5 E0.1185 F1800 ; 2
G1 X208 Y100.5 E0.1185 F1800 ; 2
G1 X208 Y98.5 E0.1185 F1800 ; 2
G1 X210 Y98.5 E0.1185 F1800 ; 2
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y106.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y106.5 E0.1185 F1800 ; 0
G1 X205 Y108.5 E0.1185 F1800 ; 0
G1 X205 Y110.5 E0.1185 F1800 ; 0
G1 X203 Y110.5 E0.1185 F1800 ; 0
G1 X203 Y108.5 E0.1185 F1800 ; 0
G1 X203 Y106.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y106.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y106.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y106.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y108.5 E0.1185 F1800 ; 1
G1 X207 Y110.5 E0.1185 F1800 ; 1
G1 E-1.4 F2100 ; retract
G1 X208 Y106.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X208 Y108.5 F10800 ; move to start
G1 X208 Y110.5 F10800 ; move to start
G1 X208 Y108.5 E0.1185 F1800 ; 4
G1 X210 Y108.5 E0.1185 F1800 ; 4
G1 X210 Y110.5 F10800 ; move to start
G1 X210 Y108.5 E0.1185 F1800 ; 4
G1 X210 Y106.5 E0.1185 F1800 ; 4
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y114.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y114.5 E0.1185 F1800 ; 0
G1 X205 Y116.5 E0.1185 F1800 ; 0
G1 X205 Y118.5 E0.1185 F1800 ; 0
G1 X203 Y118.5 E0.1185 F1800 ; 0
G1 X203 Y116.5 E0.1185 F1800 ; 0
G1 X203 Y114.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y114.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y114.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y114.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y116.5 E0.1185 F1800 ; 1
G1 X207 Y118.5 E0.1185 F1800 ; 1
G1 E-1.4 F2100 ; retract
G1 X208 Y114.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X208 Y116.5 F10800 ; move to start
G1 X210 Y116.5 E0.1185 F1800 ; 6
G1 X210 Y114.5 E0.1185 F1800 ; 6
G1 X208 Y114.5 E0.1185 F1800 ; 6
G1 X208 Y116.5 E0.1185 F1800 ; 6
G1 X208 Y118.5 E0.1185 F1800 ; 6
G1 X210 Y118.5 E0.1185 F1800 ; 6
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y122.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y122.5 E0.1185 F1800 ; 0
G1 X205 Y124.5 E0.1185 F1800 ; 0
G1 X205 Y126.5 E0.1185 F1800 ; 0
G1 X203 Y126.5 E0.1185 F1800 ; 0
G1 X203 Y124.5 E0.1185 F1800 ; 0
G1 X203 Y122.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y122.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y122.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y122.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y124.5 E0.1185 F1800 ; 1
G1 X207 Y126.5 E0.1185 F1800 ; 1
G1 E-1.4 F2100 ; retract
G1 X208 Y122.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X208 Y124.5 F10800 ; move to start
G1 X210 Y124.5 E0.1185 F1800 ; 8
G1 X210 Y122.5 E0.1185 F1800 ; 8
G1 X208 Y122.5 E0.1185 F1800 ; 8
G1 X208 Y124.5 E0.1185 F1800 ; 8
G1 X208 Y126.5 E0.1185 F1800 ; 8
G1 X210 Y126.5 E0.1185 F1800 ; 8
G1 X210 Y124.5 E0.1185 F1800 ; 8
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
G1 X203 Y130.5 F10800 ; move to start
G1 Z0.3 F1800 ; zHop
G1 E1.4 F2100 ; un-retract
G1 X205 Y130.5 E0.1185 F1800 ; 0
G1 X205 Y132.5 E0.1185 F1800 ; 0
G1 X205 Y134.5 E0.1185 F1800 ; 0
G1 X203 Y134.5 E0.1185 F1800 ; 0
G1 X203 Y132.5 E0.1185 F1800 ; 0
G1 X203 Y130.5 E0.1185 F1800 ; 0
G1 E-1.4 F2100 ; retract
G1 X206 Y130.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X206 Y130.9 E0.0237 F1800 ; dot
G1 E-1.4 F2100 ; retract
G1 X207 Y130.5 F10800 ; move to start
G1 E1.4 F2100 ; un-retract
G1 X207 Y132.5 F10800 ; move to start
G1 X207 Y134.5 F10800 ; move to start
G1 X209 Y134.5 E0.1185 F1800 ; 2
G1 X209 Y132.5 E0.1185 F1800 ; 2
G1 X207 Y132.5 E0.1185 F1800 ; 2
G1 X207 Y130.5 E0.1185 F1800 ; 2
G1 X209 Y130.5 E0.1185 F1800 ; 2
G1 E-1.4 F2100 ; retract
G1 Z0.5 F1800 ; zHop
;
; FINISH
;
M107 ; Turn off fan
;M400 ; Finish moving
M104 S0 ; Turn off hotend
M140 S0 ; Turn off bed
G1 Z30 X250 Y210 F10800 ; Move away from the print
M84 ; Disable motors
;M501 ; Load settings from EEPROM
;