; generated by PrusaSlicer 2.5.0+win64 on 2023-01-04 at 15:49:27 UTC 


;
; thumbnail begin 160x120 10132
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAAddElEQVR4Ae2d+ZMVRZ7A3x+y4+iOsz
; izszOjuK7Xiu54zCiHCs1NNzTdNFfTHN1cDTQgpwqCoHKoyDEgYAMiNysIMxsjjm4QXigRGxgKEgQo
; IOCvuf1J5ttmV1e9yqrKevVe6w/fUPodVa/yk987M3M9e/ZUYdKrVy9VU1Ojli5dqoYOHar/HSRlZW
; WxpHfv3m1k5MiRatmyZaqysrLda37Sp0+fNjJ58mT17LPPqkGDBrV7Lan07du3ncycOVPfL9fzez1I
; +vXrp1avXq0uX76sPvzwQ1VfXx/p86bY3n///v3VokWL1PTp0/X1o/5+WHjmmWfUiBEjrMbGT2Tcc2
; HgmcLFFyxYoBobG/WHk4Lnd2M8yLlz56pZs2bp60WBzivAu3z5cjV69GhnoHllyJAh6oUXXtDPJC44
; yIQJE9Snn36qvv32W7VixQo1cODARN8XBCXPgokyfPjwRJNwwIAB6qmnnlLTpk3T14kLYc4GPK+MHT
; tWLV68WM/2OPAF3RDa9fnnn9faLy50fsKDAmpmfhLYvIK2WrVqlb5vF7CUl5er5uZmde3aNXX06FH9
; HFx8rwjPYeHChRruJPCZz6yurk5bGiZiHAhzUeETAb7nnntOjRs3LjF4CBoEtY5JcAWeKaNGjdLaEF
; jiAifC7F+yZImaM2eOvl+XkCBo/9OnT6szZ85oi8PECXrv6AFPqop+vfN+X1VVlZ7YjFWYhowjgwcP
; 1vfJhAyzWoEA2oLn1XioYC7OQMQBj1mPP8LNu4bOO1sZSGYr9xwXHEDGZ8OUuQbPlOrqanX48GF19e
; pV9eabb/pq2XkVj6ojI/5DNQ/7TzVlUHff78EXZrIASdg1kz7fSZMmqfnz52sNGwnAOOCZwsNihuGc
; 2oKHoL7xR4AwDfCCHnRDQ4PW3hUVFZGgmDdvnh5MV/6ZjfB88As/++wzNWXKFD1x0HivVT2g4RM5MP
; wuDaRoQywU9zp16tRYky3uM4cFLJn43aEAJoVPhIsxQESDYRfmgaA1icLM96YJnVeAj0kzfvz40Pdi
; wl566SU1ceLEwPfwm9ISJurx48d1pLxxyRwNmwmfKZuqu6jGsSO1uzFs2DAnkyDqGOCiwEFTU1OgS2
; UNYNQAY8yYMTpdE+SU8lCY1WhLV+Alebg8KCZDkFZD66xcuVL/njQhCxPu7/CicYHgmXJo1L1qYWVX
; J/AlARF3BZcHrehVSli9bdu25QcwCnjml/Ow8OvQGObfGWx8BH5MUvBcPlhSEqRS+K9oMx4QE4WAAN
; 8xS/hGD+ypdtXcYwWfVxuGBShpg8hzZMzxD+WzpJw+//xzdf78eX8A44LnFUkGMwPwuUjfFBN4pvkE
; MlIUAEe0SKBBojVL8JB5gx+NDJ7XN5xS3j2V5xZlzAgy8Q3XrVunLl26pI4dO6Y1ZC4t+Eytd/DgQe
; 1rFQt0QYMNhK+++qo6cOCAnjRZglfRv4/WYEngM2VZ5cP6O/nuLEBkMr///vs6qt+1a5f2E/l7Li3w
; uADEE4Vxk5IM5gFkAV7YgOOT4uthHjAbBCho8Czgm1nR1Rl4ppCuwZyb1yoEiFjBc+fOqZMnT+p8L0
; oJHpjwuTTgg3b8J6JH80YIzRlY79/TAs92wInW8AGJjM2/ky/ElwXIQsG3auiDqcDXJl3TYtb9ru0a
; Qkqhu3fvbs1lkos0NSJg5lyCxxdTHZg9e3bgjBDNyOCmAV6UwZY6rhTl/QRTzHuYPFG+m9kdRWoHxQ
; s04grmfdiAstRAxPKdOnVKnT17Vls+Px4IVnOu4IN20i+1tbVW5jVuMjgpdCKYWgIN0kI27yfHyYPk
; oUWFK0wWDfljwcDzC1Cq+z6hVg6+v51mjDMWPJ+NGzeqK1eu6Hp2WNNDLil4CLkyTJU4lraCBgqqUa
; YFHg+ICgGpAe43ihYjIYw2xIVwAR5ab9uw+zKBT2TnkM5qf/W/t9GMEqxEBZEcMAnzixcv6o4eqWHH
; AtAGPMo9ku9LEtnilEqXRlrgIXSXoPV4UHHNJr+ZTiBcCACOC9/8IY9lCh7QAV8+zRjFNFN5uXDhgv
; r44499q0uRALSBD1PLRU3HMip4puCU8n2SDHYFnQjmE20LQFGACxKzyB/lc4MH9FVrq/4rU/gALwg+
; U8zUTRCIuDCHDh3SJveNN97QAVvQGIcCaAMeN4D5InIMU6824JliJoPlhyYFT+q4uAlJTaZX6FB58c
; UXtQth8/768ifUwTx13LTl0PA7VHP5rfq/tp/xS93I2BBsfvXVV1qk7hs2xoEA2sBHREh6BW3lQusF
; CSocbcUAJ4EPLSUNo67hM4WcFvVkZn/Qe5a3aJOswEP2Vt1upfWCTHLjwMdanytan8ZZ0isUGeI0Pb
; QB0Aa+GTNmaO3EDaQFnmluiY6JqqkhRgVP6riAkcRPiyKUldC0uBDm3wudXgkyuWagEVXeHNxZrRvQ
; WQ3v94TOHpw4cUL7e7gg/Ma446wBDAMPEEiXRC2lxQXPKzj7JCxtk8EEGC+//LIGohDgmUIQxb3iQv
; D/xRBobB98W+zP//ewO9SWQbeqTQN+r+XVhgod4X7wwQftArm4EOYFEOjQQgx+ocEzBRVPgELg4/e6
; APD000/rqJxAI23Y0KxBMm3iBLWnvnum8AHersrbY39+V2XnVvDW9/udavzDzWrZqF7q9XVr2gRy+Q
; IUKwBlcZEJHg8Yc+tXrXAJXxSzyj1JMljydwKD1HFJbhcSND+ZNbhbpuChtaIGGt7Pv1H+g9Z76cl/
; VaPu/rla1es3+vVN1ff7BiVxIcyJiZVWKXwY/CdpIsxK6wUJyWDp9gUQymj4XiS1swDOlNVV6dZxw8
; Q2vRIke4be3goe8tQj/6ImP/AL/XfzffnqyVEhzEkNlzB6w4YNrQ2jxaD1gkwtk4ZJsnnzZp3EzhI6
; ZEx5r8wDDUwu2ivOZw8Pvx5oCHire/2bqrv3RrX88V/n/Vy+erIthBpAtAcRDdqE9IftouVCwecFBt
; +UQIPGB0CMqv2SAmfK4so/ZQYdkq+iYSPeQOOZrreo8ffdpHZYBi9BVRNbCHOkOfADpY4rvpYsLnIB
; nyvwiCxxF6Rsx99wFTDJNslgl+Ch9Yqtjhvn82agMemBf1YLH+0U67uCqiZhEGoA/drk8bVkcVExaD
; 2p4waBJqv+vRGwS+hEFhRxHddW65mBxnPdf6Vq7rxBrenz20T3FVQ1yQdhzg8+EdIvaEeiy0LBFwQX
; Wg7fL5+Go2ePbhUqNWmAN2Rgvw4XaDQ99EvfQCOuSIBi21GTs/H1aC6kiTTtbhUvUJTQiHBJB9n6d0
; waSQa7NrlZBhpSx00SaGyvuK1doCHpFdfiF6DEBpA3yu4HJIMLofVo8cLkcl0b8LzAoLWl/T8pfMuH
; PpLKINlKkjougsnePPAHrTf/T5201tuRoEpiI2hD1rfkgzBnA58IA03kGbQpjwv4ZEGQJJyjgmcKGp
; QoGZh/rIGGN70yoctNanG3XxX0N7DOJWhFXi5OpCuLi9BOLuFDu5Je4b9JwPMKET1mmS6OUgo0XNZx
; Sa/U3nOj+nP/32Xye/QGSv9I11gBGObnia/FMjsXJpd2JnKRYXXcuGaUKJrePeDO977KQf3U2uo/ZD
; JIImg9l3VcAo3pD96sDg6Lr0ldCCa5rvcf20CYiwOfKaRxZHFRHPgoqVHH5Xtcaj0/IYiiYUEWF5l/
; RxoqepZcw2ibz9e0Ta+kHWhEFXKMlQ/enh/AKPAJVPha5AzJ0UWBD+0JfKyoSxM8r1BJIV1DE4PA90
; LGgQZaL4nJJVCxqeNmIQQ7VFfINQqAAmEuKXwmXKQ+SAYzyPngwxcjryepkkLCJ8CRYGfSLJhc15Je
; uTfTAXJdx80i0AgS6smAJxIIYBL4TMHXAi5zYx8TKLpuCDR4PW2T6weeKcVQx00j0OBvWf4uBK2HBj
; bh8wJIqiwygDZ+HoEEvhYdNiZMNItKQjtL8CoH9VfbarJNrwAeZjPu5711XBpG49ZxXQs+pxc8E0AC
; WDggnZdzDZ8prB+Qhecklfl3obSeH3jI7CHZdiq70Hp+DaNJ67guhCgb3zMIPqSxvJt65ZVXWlv6c2
; nBZ6ZX9u/fr1u9CgFfEHjI6qqHMh0gwCtEw2gWgtnH/OeDb8KjndXnx/+uPvnkE71foDWAceAjsiXv
; BniAQTI433qNNOGrKy/LNNAgrZI00PCr44Y1jBZKCHjygYdMHdRNL5NF2HD9m2++0XV+5wACE3QTaE
; jbvAhpD0pj3kpHmlov6/RK0tapAxnVcW0kKNDwSlPtUF2TF0bIGW/fvl0fyJNzCR/ajdQGDa2A4afp
; eA9t/zigaWu9rAMNlw2j+HjFlF7JF2i0mtxud6pJ48bocfLjhTa7nCv4WIeL1sO5DPP1EDkjBC3pGr
; 4FlV3VkRHZDY7rNnkaRvGviiXQoKwXBt/s2krNRBg3ORfwUdqS9cM28InZJRlMwysVERfwkV4p9Tpu
; UMNo1nVchAkQBl5997vUtAl11hsJJAJQNv7BsbQFz8/no+GVerJtt4offMVQxyXQiFvHJdBoLi9cw2
; hUIccYBt+MoWXa/5dxjg2gzQfZbSrOxj9BUMkBNuQMo5rcrAMNNF4SkxtUxy2WQEPquEEyqksnNXPc
; CN+avnMAZeMftuYKCjTiACiAEZzIqrcw+LJOryBovVJvGA0Sbx3XTxqevE9NmVgfyEJkAPO9WTb+od
; 4rKRdX8JlCmoZuFa4TBGAxBBodqWHUFNv0ysxRg9vtBpYIwKA38UXU7kgkM/hpwieCP0jDK/Vkb6Dx
; +rD7Mx0gqeNSEsP0Rk0w+238g9kthkDDJr1CoDF9cr3VJlCJAZSNf6R0Ugj4TKFRFZOPr1kMddyVPX
; /TAswv1PC7fqZq7/25Gnffjaq+xWwuaHHSN4Zor2Kv49oEGtOG9LTeETYSgH4vUkajnIY28mrEQgAo
; Wo9oe+/MwZkOEJoOM1lz589U1R3/1A7AhvtvUlNbwFxd5h+1FnMd1ybQGE2gUV8beRuUUADp3SN6Mf
; 8IcPhg7IrqZ44Lpf2KqY4LKMPvuiEUwBkP3dwSWPzgG3aEOm5jeXedq41zRkoogLL7gZyLRrt6vgNc
; Cqn9imnjH4IDWwBfb6nd8hlvHRcNWmp13Jl11e2qVU4BFPPL7gM7duwIbKkvJHzFWMdlwGwB3F3Z2X
; fjn1Kq407v84Ca2zRNBxre8XEOIO3xJJXRgphe2uazArCYN/5Z+FinUACf7tqp3cY/xVTHDWsY1RWN
; mv6t2zOjmLw5WacA0pFAlCm1O0kG09GSBMCo4JXCxj8M4OJut6iRd9/gCyAaLs2Nf5KITcNoQ4+7Vd
; PEcW1KopRJWa9N8JEKgFzA7wU6GWQr3LS1X6lt/AOIW1sGdG3f32rzisYr5jquTaAxo6pMp7y82g4h
; CxHlQJ5IAOZ7URaPEA2nBV+pb/zjreMWW8OoTR139oRRVps4YRnDDuRxCqAIm/vgD9iei2ar9X7a+C
; c9sQk0JvbsohonT/INNIKEMinakAJFwQDki+Q8YLPdJi6AP238k57YNozOqq1sU2u3FcYXM01ZlnU+
; YT6hMwAFLC6KWc534XyBxtrq7E+KdH2ASzFs/IPYNow2jq/V6zKiwucdcywjy27zVUecAihCBwRq2O
; 84rKAbb6x4vKQ3/vHWcTG55gEuWYtNHXd6ZS+9Ntsv0IgDIIJbRhbF75AgG7ZyUeETwRHFIaUvMAzA
; YkivJDG5pV7H1YHGxLHajZL6ugv4TBHLaAYoqQIoQmhO8lq6YQcUUXoF+TFt/OPbvVLRQzeVEGgkgS
; 8MQNMy4lsWDEBEDrqhkiI32xEPcCn2jX+8MntcjYbC28ybFoAilHPlqNyCACiaj5m2dOakzNMrSdvk
; S3XjHzPQ4MROzKHfUoY04ROhlIdv6O20Sg1AJOuTIl1v/LPsHyaulOq4TcMH6DXXQQu40tZ+pv+H2c
; cyBlXbqLw4AXDwgL56J/QsB8j1xj+lWMedNaVeu0P5tiopBIBehgCQlj/ZxpnIGTNNTjkxgFkfSZ/W
; AS6l1DDaVN1bD7IZaGSt/bwia8jZFZe9I/m33iE1CYDLKx/OdHCowyYxucW+8Y9NemVe/Si1Zs0aPa
; D54MsaQK5PYEKzMwDy79gAovU60kmRpVjHZeOfyeOvb4EBfHQuUZkoRvjoN2WFoyznlXoy9x0ZwPkd
; 4KTIUq/jzh5TqQ8L8kKGeZMDeVzAlxRA/k1DK72l3r1i+G7qydYAEmisrSrtOq4ZaBTTAS6ITR23gf
; W49XXtADOF8qgcyJOl9iP9QmVEegi9XMlqTCsA68ufKOk6bofY+KeqTNdbw/w8hGBENgEvVN7PZIZ6
; M5o4KAdorkUPBTDrQCOtA1xKbeMfmyDDK4AgXe2FABAzy+ajROR8RxBTVgBy8nUp13GRjrDxz9RJDa
; HplXxBhxzII1CkBR8+KVqP0l8+hebdi8gXQE68znJwfowHuHiFjX+IHqOCF2RyKZOyB6O5uMgFfHyG
; ThhSLEyUKPC1A5AzXTnpOssBSnqAi1/DaKnVcWdMbtBVA1fwidBGL8tuXQCIaUfrUfoLSsFEAnBcj3
; v1aq8sBqejH+ASZeOfOODZBhu8j7QIvZzetSBR4KOOSznNu29QFPjaAVjb7R41rSUtwUx9u+YOdaRA
; A9SRD3Cx2vjn/k6qaUJtm4bRNOAzBa2FNsRniwIfwFHJAMB8gYYNfIEAIgsfu0WbszQH56cDXH7Y+C
; dOoBEXPhHMPE0CtstugRaTG7RvUCwASVqK/TYBRGY+/EvtR6UxOK4PcCnFjX9m1VW3ObO4kPCZZhdt
; RqQcdG4z1yGnKJuFuoJPA3jlyhV15MgR/SC8AIosapnJ+6rcVQtc1nFLceMfAo2p9eMCG0YLAZ7X7L
; IBKDlD74GSmGi0npxu5RI+DSCLir744gt15swZNb+mzBdA0YZJA5SOfoCLVcNoTf82ZbJigM8UeMDH
; Y3JwEgIBC6Y6DfhafUAoP3TokHpv9+ZAAEXiBihhG/+ESak3jE7t1UWtWvpsaMNo2uDZBBxowT179r
; Su64gKX2QA2f2eZkF6tf7+9m41p8eteSGMEqC4aBjtKBv/4ENJMrhY4WMtByYXl4x6siy7TQM+zqrO
; UbtDJItNHuqv7xxSG6bX5IVQApR82vCnjX86qVkTRqrq6upWkBhYfC3bfF+hwMPkYm5lP0BTG7L7AT
; 6ia/g0gH6bUZLrWb9+vTq4bnmoNgwKUDryxj82ddzrG/9M9E2vyGBLMjhN8Gzgo4WL3jxZz2vWeIUH
; omS0uEv4NIBBO+RzA9QP/7r/LbW8pluoNgQUBmdfi9ZKYh6LuWEUf9MqvVI7RA9mmHbD9SEZbNZ8XY
; IXBh+v4xaQYvFuuebHBDxgnv0OIrSFzxpAEcxH85bX1Y4lM0IDlBdbyl/Pt2iHuKmbjrDxT9OUiZHq
; uPiDaB+SwYXUeoyr2TAaBp8ISWhcCLpfksLXCmAYhDwoyH/3wE717IAuoSBGTd0E1XFLqWF0WmXP1o
; 1/4vh2mDd8LZLBacPH2hHg89vVysbP4324EGhO/j8ufNYAipC/OnRgn9q6oN4awrDUTUfY+GdWQ51V
; HTcMHJpOgZD1smmAh2amgUC2UIkDnyly6LgssYwKXxsAbSHE/nNg4Ttb14QGKPlSN8W+8Y9NemVaRX
; cdNear40aFiM+Q+kBDRdm5NAw+/E1JryQFzzS73CMuBA2vUeFrB6AthNw0s+jtt5rVy+P7RzLJ+HYE
; Kn6BRinVcWePHdamjpvUbHqFIIYABV8rCXjcGwllVsz5HS6YBD5T4EF2P7CFLzaAIuSGNq5fq7Y9Nz
; 2SNlza49dt6ril1jDa2DBeWwLX0HmFa2Ay5WzmKOAhTBC0HtrP73VX8InAAyYZ02wDny+AUSHkYcyd
; O1f9ZXezdYBCGW1JjxLc+KfmektS2uB5heBGfC0b8BDquOQZ/TaWdw2eV5gwFDe4ViwAo0KIYDL27t
; qpdj4/0wpC0iultPHPzEnj2xzgUmghyGGnKaLlfOAR2eI/soTTT1OmDZ9oPnhg0pC2CYKvd+/ewQDG
; gRAfA7/lg8N7ndaT0xKrjX+qemv/Jg0/L0z8ACMZjNPvd1YHOT1MLjk+F+BFhc8LGNels4Ycp9/rpH
; GcAiiCyfjbX444qSenIbbplRmjK/VgFgN4Xt9OfC3+zcTHDQJOs45bKPDC/D0aHNDeWBD+LScv8fdc
; 2BfH/QGYgo0bN6q3N7yo5jx+W6x6chpiu/HPpHFjIqVB0obOL7olGUx3DRrRe2JB3HFzDZ8I0TH1ZE
; CUQ49CTXASCHkItHd999136v8+fF8tH9bVup6chthu/DOnrkpvdyY+VDFBZwqfJweJJlyxYoX2tQqt
; 9WzhQ5jMJNm5VyYM92kNYFQIaXA9evSohm/z5s06DbCjeavasbTJqp7s2iTb1nGnTRijZyoPS5LBhW
; yJshVMmFnH5Z4ZVBY3FZPWE5GTFHAdgA63BhjhJBflojY/BLPw9ddf6zZ/fBKZkQwk5uLYwbdC0zUE
; KK7WJ1sd4DL0+gEuXmDoUpEDebIEzhTKdMBnLiCSZ0+wxDOWrXCz1np8P3lMUjI8D+AT4XVYycW5gS
; CfjxPXr127pvbt26cp93sfjvORtw+q9SkHKLaBRtPY4XkbAKR+SiWhUJD5iRwMFLbxD8lgtAtaJ0v4
; 5MwQrJ+kXPwkx4tJIaS74uTJk+r8+fPaFOR7QAiDip+1f+2y2A2v+cSmYbT+ifvU5IZ6a4hkp6mgpY
; tpCk0gNhv/mP43EwZg/cYiTfAQWXrApAkCrw2AcSHkx7322mvq8uXL6tixY/pB2ap+HhLZ+nd2b7dq
; eLVZn2xbx20aWWF93KgpciBPWDLYlfB8AQl/NGzjHz+RZLCAG2eMo8BHZIvWwxXgc2HwlZWV/QBgVA
; jxi9577z116dIlDSE+XtQHhOBQb/7zerXdop6MNgwyyVEOcPErykeBgsQqmt6bc3MpUTf+CRJ+Ky6E
; JIPT0npkDbAQjGcYeAJfOwBtIeThnzt3TpvdsHUCNsKgYi7+Z+/20ADF2+QatY7rChB8XCK7oEJ/Eo
; m68U+QmGNG0pf8G1rcJXzcLzzI6jlb8AIBzAchDu7evXvV1atX1c6dO31/TJIHhlY9sGeXVcMrGu8N
; izru2Ed+r2ZNrrc+7T2KoF2I5KhCxP0O8/fLxj/41Em0XtD48f34ZkTSLrQerWKSJcgXaATBFwigH4
; TkmE6dOqXOnj2rH3i+H5oEQhxXkpWHNr8SapJp288HX+OgbtrPTDtalcVFfjXYMOhEZOOfoOxBEvC8
; QnoM0HkuccDj/Wg8NB+TMIrJtQZQBD+Hkhp7yJBcxqG1/aFJQMSn2L99s9owY3gsAJtqh0ZqX0oqkg
; wmTRIGmyk8X4ry+Ghx/Wjb8TAFH5N0jWgvW8EKovXICsTVetYAMrOPHz+uLl68qHdO4IHG+bFxIcTE
; r3v1ZdW8qNFXG/oBKHXcNAOEIK3Gf9G4mDmbqFU2/jFXmKUJnVe4X6wZ2sxGC/Lb5ATMJFqvDYB8md
; /FMCkXLlxQH330kU5quvjBcSDkIfGA3tm5pV2A4gVwdm2lntFxr2OrtcKEZ5ovGcw1cGn8DnApBHje
; sSZ9JtuzBVlB0k9oae7BFXwaQHwB1KncGD4IGxVhcrds2aJnctQoOQ0Y0RZvbW9Wbxr1ZAGwQddx6y
; IPZpqCf8VaDKJ7E2oGmWdOVGoLu6tnnk+7Mc5oYyJw8+/snCE7qboED+nVq9f1UhyJQ+p1zMjTp0+r
; L7/8MrCJMEsQmYnMVNlACQBnDC3TUV0xQOcn1JPJj5H4RiNKHbcYoPMTWJDdD2CCdJC3jpsUPsATyf
; FBLsZ2XN9//7169913tRa0uVlXDykqjGiPD//3ffXx395RmzZtiu28F0rwZbdu3apWrlwZWKZ0/Syj
; gmcKz/fw4cMaQBeBRhB8GkAuduLECV3HRbtgNjj3AfNge8OuH14+IGVtBPe5YcOG1jJgXN8vbeG+0H
; qYMCJ7fEPv0sViAQ8hRcPzZdJQBiRCD4IwCXgi/w9fBNuT90IBBwAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.60mm
; perimeters extrusion width = 0.50mm
; infill extrusion width = 0.50mm
; solid infill extrusion width = 0.50mm
; top infill extrusion width = 0.45mm
; first layer extrusion width = 0.42mm

M73 P0 R0.45 
M73 Q0 S0.45 
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2 
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2 
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec 
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.11.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S230 ; set extruder temp
M140 S0 ; set bed temp
M109 S230 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling

G1 Z0.2 F720 
G1 Y-3 F1000 ; go outside print area 
G92 E0 
G1 X60 E9 F1000 ; intro line 
G1 X100 E9 F1000 ; intro line

G92 E0 
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0 ; Filament gcode LA 1.5
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G0 Z0.2 F720 ; Move to z height
G1 E-0.8 F1800 ; Retract
G1 Z0.4 F720 ; Z hop
G0 X10.0 Y0.4356 F4800 ; Moving to line position
G1 Z0.2 F720 ; Z hop return
G1 E0.8 F1800 ; Un-retract
M204 S800
; printing line start id:0 copy 0 
G1 X10.0 Y150.0 E9.32725 F2400 ; Create Line 
; stop printing line id:0 copy 0


G1 Z9 F720 ; Move print head up 
G1 X0 Y200 F3600 ; park 
G1 Z57 F720 ; Move print head further up 
G4 ; wait 
M221 S100 ; reset flow

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan 
M84 ; disable motors 
M73 P100 R0 
M73 Q100 S0

; filament used [mm] = 30
; filament used [cm3] = 0.05
; filament used [g] = 0.08
; filament cost = 0.01
; total filament used [g] = 0.08
; total filament cost = 0.01
; estimated printing time (normal mode) = 00m 17s
; estimated printing time (silent mode) = 00m 17s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.6
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 230
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.3
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 230
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_solid_infill_speed = 40
; top_solid_layers = 4
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end