; generated by PrusaSlicer 2.5.0+win64 on 2023-01-10 at 19:36:16 UTC 




M73 P0 R0.45 
M73 Q0 S0.45 
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2 
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2 
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec 
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.11.0 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S230 ; set extruder temp
M140 S0 ; set bed temp
M109 S230 ; wait for extruder temp
G28 W ; home all without mesh bed level
G1 Z0.2 F720 
G1 Y186 F1000 
G92 E0 
G1 X40 E9 F1000 ; intro line 
G1 X60 E9 F1000 ; intro line

G92 E0 
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M907 E538 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0 ; Filament gcode LA 1.5
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G0 Z0.2 F720 ; Move to z height
G0 X0.0 Y0.0 F4800 ; Moving to plane position
M204 S800
; printing plane start id:0 copy 0 
G1 E-1.5 F1800 ; Retract
G1 Z0.4 F720 ; Z hop
G0 X35.4356 Y5.0 F4800 ; Move to box start
G1 Z0.2 F720 ; Z hop return
G1 E1.5 F1800 ; Un-retract
G1 X35.4356 Y35.0 E1.87088 F2400 ; Draw perimeter (up)
G1 X65.4356 Y35.0 E1.87088 F2400 ; Draw perimeter (right)
G1 X65.4356 Y5.0 E1.87088 F2400 ; Draw perimeter (down)
G1 X35.4356 Y5.0 E1.87088 F2400 ; Draw perimeter (down)
G0 X35.8712 Y5.4356 F4800 ; Step inwards to print next perimeter
G1 X35.8712 Y34.5644 E1.81655 F2400 ; Draw perimeter (up)
G1 X65.0 Y34.5644 E1.81655 F2400 ; Draw perimeter (right)
G1 X65.0 Y5.4356 E1.81655 F2400 ; Draw perimeter (down)
G1 X35.8712 Y5.4356 E1.81655 F2400 ; Draw perimeter (down)
G0 X36.3069 Y5.8712 F4800 ; Step inwards to print next perimeter
G1 X36.3069 Y34.1288 E1.76222 F2400 ; Draw perimeter (up)
G1 X64.5644 Y34.1288 E1.76222 F2400 ; Draw perimeter (right)
G1 X64.5644 Y5.8712 E1.76222 F2400 ; Draw perimeter (down)
G1 X36.3069 Y5.8712 E1.76222 F2400 ; Draw perimeter (down)
G0 X36.7425 Y6.3069 F4800 ; Step inwards to print next perimeter
G1 X36.7425 Y33.6931 E1.70788 F2400 ; Draw perimeter (up)
G1 X64.1288 Y33.6931 E1.70788 F2400 ; Draw perimeter (right)
G1 X64.1288 Y6.3069 E1.70788 F2400 ; Draw perimeter (down)
G1 X36.7425 Y6.3069 E1.70788 F2400 ; Draw perimeter (down)
G0 X36.8514 Y6.4158 F4800 ; Move to fill start
G0 X37.4674 Y6.4158 F4800 ; Move
G1 X36.8514 Y7.0318 E0.05433 F2400 ; Fill
G0 X36.8514 Y7.6479 F4800 ; Move
G1 X38.0835 Y6.4158 E0.10867 F2400 ; Fill
G0 X38.6996 Y6.4158 F4800 ; Move
G1 X36.8514 Y8.2639 E0.163 F2400 ; Fill
G0 X36.8514 Y8.88 F4800 ; Move
G1 X39.3156 Y6.4158 E0.21733 F2400 ; Fill
G0 X39.9317 Y6.4158 F4800 ; Move
G1 X36.8514 Y9.4961 E0.27166 F2400 ; Fill
G0 X36.8514 Y10.1121 F4800 ; Move
G1 X40.5477 Y6.4158 E0.326 F2400 ; Fill
G0 X41.1638 Y6.4158 F4800 ; Move
G1 X36.8514 Y10.7282 E0.38033 F2400 ; Fill
G0 X36.8514 Y11.3442 F4800 ; Move
G1 X41.7799 Y6.4158 E0.43466 F2400 ; Fill
G0 X42.3959 Y6.4158 F4800 ; Move
G1 X36.8514 Y11.9603 E0.489 F2400 ; Fill
G0 X36.8514 Y12.5764 F4800 ; Move
G1 X43.012 Y6.4158 E0.54333 F2400 ; Fill
G0 X43.628 Y6.4158 F4800 ; Move
G1 X36.8514 Y13.1924 E0.59766 F2400 ; Fill
G0 X36.8514 Y13.8085 F4800 ; Move
G1 X44.2441 Y6.4158 E0.65199 F2400 ; Fill
G0 X44.8601 Y6.4158 F4800 ; Move
G1 X36.8514 Y14.4245 E0.70633 F2400 ; Fill
G0 X36.8514 Y15.0406 F4800 ; Move
G1 X45.4762 Y6.4158 E0.76066 F2400 ; Fill
G0 X46.0923 Y6.4158 F4800 ; Move
G1 X36.8514 Y15.6566 E0.81499 F2400 ; Fill
G0 X36.8514 Y16.2727 F4800 ; Move
G1 X46.7083 Y6.4158 E0.86933 F2400 ; Fill
G0 X47.3244 Y6.4158 F4800 ; Move
G1 X36.8514 Y16.8888 E0.92366 F2400 ; Fill
G0 X36.8514 Y17.5048 F4800 ; Move
G1 X47.9404 Y6.4158 E0.97799 F2400 ; Fill
G0 X48.5565 Y6.4158 F4800 ; Move
G1 X36.8514 Y18.1209 E1.03232 F2400 ; Fill
G0 X36.8514 Y18.7369 F4800 ; Move
G1 X49.1726 Y6.4158 E1.08666 F2400 ; Fill
G0 X49.7886 Y6.4158 F4800 ; Move
G1 X36.8514 Y19.353 E1.14099 F2400 ; Fill
G0 X36.8514 Y19.9691 F4800 ; Move
G1 X50.4047 Y6.4158 E1.19532 F2400 ; Fill
G0 X51.0207 Y6.4158 F4800 ; Move
G1 X36.8514 Y20.5851 E1.24966 F2400 ; Fill
G0 X36.8514 Y21.2012 F4800 ; Move
G1 X51.6368 Y6.4158 E1.30399 F2400 ; Fill
G0 X52.2529 Y6.4158 F4800 ; Move
G1 X36.8514 Y21.8172 E1.35832 F2400 ; Fill
G0 X36.8514 Y22.4333 F4800 ; Move
G1 X52.8689 Y6.4158 E1.41265 F2400 ; Fill
G0 X53.485 Y6.4158 F4800 ; Move
G1 X36.8514 Y23.0494 E1.46699 F2400 ; Fill
G0 X36.8514 Y23.6654 F4800 ; Move
G1 X54.101 Y6.4158 E1.52132 F2400 ; Fill
G0 X54.7171 Y6.4158 F4800 ; Move
G1 X36.8514 Y24.2815 E1.57565 F2400 ; Fill
G0 X36.8514 Y24.8975 F4800 ; Move
G1 X55.3332 Y6.4158 E1.62999 F2400 ; Fill
G0 X55.9492 Y6.4158 F4800 ; Move
G1 X36.8514 Y25.5136 E1.68432 F2400 ; Fill
G0 X36.8514 Y26.1296 F4800 ; Move
G1 X56.5653 Y6.4158 E1.73865 F2400 ; Fill
G0 X57.1813 Y6.4158 F4800 ; Move
G1 X36.8514 Y26.7457 E1.79298 F2400 ; Fill
G0 X36.8514 Y27.3618 F4800 ; Move
G1 X57.7974 Y6.4158 E1.84732 F2400 ; Fill
G0 X58.4134 Y6.4158 F4800 ; Move
G1 X36.8514 Y27.9778 E1.90165 F2400 ; Fill
G0 X36.8514 Y28.5939 F4800 ; Move
G1 X59.0295 Y6.4158 E1.95598 F2400 ; Fill
G0 X59.6456 Y6.4158 F4800 ; Move
G1 X36.8514 Y29.2099 E2.01032 F2400 ; Fill
G0 X36.8514 Y29.826 F4800 ; Move
G1 X60.2616 Y6.4158 E2.06465 F2400 ; Fill
G0 X60.8777 Y6.4158 F4800 ; Move
G1 X36.8514 Y30.4421 E2.11898 F2400 ; Fill
G0 X36.8514 Y31.0581 F4800 ; Move
G1 X61.4937 Y6.4158 E2.17331 F2400 ; Fill
G0 X62.1098 Y6.4158 F4800 ; Move
G1 X36.8514 Y31.6742 E2.22765 F2400 ; Fill
G0 X36.8514 Y32.2902 F4800 ; Move
G1 X62.7259 Y6.4158 E2.28198 F2400 ; Fill
G0 X63.3419 Y6.4158 F4800 ; Move
G1 X36.8514 Y32.9063 E2.33631 F2400 ; Fill
G0 X36.8514 Y33.5224 F4800 ; Move
G1 X63.958 Y6.4158 E2.39065 F2400 ; Fill
G0 X64.0199 Y6.9699 F4800 ; Move
G1 X37.4056 Y33.5842 E2.34723 F2400 ; Fill
G0 X38.0216 Y33.5842 F4800 ; Move
G1 X64.0199 Y7.586 E2.29289 F2400 ; Fill
G0 X64.0199 Y8.2021 F4800 ; Move
G1 X38.6377 Y33.5842 E2.23856 F2400 ; Fill
G0 X39.2537 Y33.5842 F4800 ; Move
G1 X64.0199 Y8.8181 E2.18423 F2400 ; Fill
G0 X64.0199 Y9.4342 F4800 ; Move
G1 X39.8698 Y33.5842 E2.1299 F2400 ; Fill
G0 X40.4859 Y33.5842 F4800 ; Move
G1 X64.0199 Y10.0502 E2.07556 F2400 ; Fill
G0 X64.0199 Y10.6663 F4800 ; Move
G1 X41.1019 Y33.5842 E2.02123 F2400 ; Fill
G0 X41.718 Y33.5842 F4800 ; Move
G1 X64.0199 Y11.2824 E1.9669 F2400 ; Fill
G0 X64.0199 Y11.8984 F4800 ; Move
G1 X42.334 Y33.5842 E1.91256 F2400 ; Fill
G0 X42.9501 Y33.5842 F4800 ; Move
G1 X64.0199 Y12.5145 E1.85823 F2400 ; Fill
G0 X64.0199 Y13.1305 F4800 ; Move
G1 X43.5662 Y33.5842 E1.8039 F2400 ; Fill
G0 X44.1822 Y33.5842 F4800 ; Move
G1 X64.0199 Y13.7466 E1.74957 F2400 ; Fill
G0 X64.0199 Y14.3626 F4800 ; Move
G1 X44.7983 Y33.5842 E1.69523 F2400 ; Fill
G0 X45.4143 Y33.5842 F4800 ; Move
G1 X64.0199 Y14.9787 E1.6409 F2400 ; Fill
G0 X64.0199 Y15.5948 F4800 ; Move
G1 X46.0304 Y33.5842 E1.58657 F2400 ; Fill
G0 X46.6464 Y33.5842 F4800 ; Move
G1 X64.0199 Y16.2108 E1.53223 F2400 ; Fill
G0 X64.0199 Y16.8269 F4800 ; Move
G1 X47.2625 Y33.5842 E1.4779 F2400 ; Fill
G0 X47.8786 Y33.5842 F4800 ; Move
G1 X64.0199 Y17.4429 E1.42357 F2400 ; Fill
G0 X64.0199 Y18.059 F4800 ; Move
G1 X48.4946 Y33.5842 E1.36924 F2400 ; Fill
G0 X49.1107 Y33.5842 F4800 ; Move
G1 X64.0199 Y18.6751 E1.3149 F2400 ; Fill
G0 X64.0199 Y19.2911 F4800 ; Move
G1 X49.7267 Y33.5842 E1.26057 F2400 ; Fill
G0 X50.3428 Y33.5842 F4800 ; Move
G1 X64.0199 Y19.9072 E1.20624 F2400 ; Fill
G0 X64.0199 Y20.5232 F4800 ; Move
G1 X50.9589 Y33.5842 E1.1519 F2400 ; Fill
G0 X51.5749 Y33.5842 F4800 ; Move
G1 X64.0199 Y21.1393 E1.09757 F2400 ; Fill
G0 X64.0199 Y21.7554 F4800 ; Move
G1 X52.191 Y33.5842 E1.04324 F2400 ; Fill
G0 X52.807 Y33.5842 F4800 ; Move
G1 X64.0199 Y22.3714 E0.98891 F2400 ; Fill
G0 X64.0199 Y22.9875 F4800 ; Move
G1 X53.4231 Y33.5842 E0.93457 F2400 ; Fill
G0 X54.0392 Y33.5842 F4800 ; Move
G1 X64.0199 Y23.6035 E0.88024 F2400 ; Fill
G0 X64.0199 Y24.2196 F4800 ; Move
G1 X54.6552 Y33.5842 E0.82591 F2400 ; Fill
G0 X55.2713 Y33.5842 F4800 ; Move
G1 X64.0199 Y24.8357 E0.77158 F2400 ; Fill
G0 X64.0199 Y25.4517 F4800 ; Move
G1 X55.8873 Y33.5842 E0.71724 F2400 ; Fill
G0 X56.5034 Y33.5842 F4800 ; Move
G1 X64.0199 Y26.0678 E0.66291 F2400 ; Fill
G0 X64.0199 Y26.6838 F4800 ; Move
G1 X57.1194 Y33.5842 E0.60858 F2400 ; Fill
G0 X57.7355 Y33.5842 F4800 ; Move
G1 X64.0199 Y27.2999 E0.55424 F2400 ; Fill
G0 X64.0199 Y27.9159 F4800 ; Move
G1 X58.3516 Y33.5842 E0.49991 F2400 ; Fill
G0 X58.9676 Y33.5842 F4800 ; Move
G1 X64.0199 Y28.532 E0.44558 F2400 ; Fill
G0 X64.0199 Y29.1481 F4800 ; Move
G1 X59.5837 Y33.5842 E0.39125 F2400 ; Fill
G0 X60.1997 Y33.5842 F4800 ; Move
G1 X64.0199 Y29.7641 E0.33691 F2400 ; Fill
G0 X64.0199 Y30.3802 F4800 ; Move
G1 X60.8158 Y33.5842 E0.28258 F2400 ; Fill
G0 X61.4319 Y33.5842 F4800 ; Move
G1 X64.0199 Y30.9962 E0.22825 F2400 ; Fill
G0 X64.0199 Y31.6123 F4800 ; Move
G1 X62.0479 Y33.5842 E0.17391 F2400 ; Fill
G0 X62.664 Y33.5842 F4800 ; Move
G1 X64.0199 Y32.2284 E0.11958 F2400 ; Fill
G0 X64.0199 Y32.8444 F4800 ; Move
G1 X63.28 Y33.5842 E0.06525 F2400 ; Fill
G0 X63.8961 Y33.5842 F4800 ; Move
G1 X64.0199 Y33.4605 E0.01092 F2400 ; Fill
; stop printing plane id:0 copy 0
G1 Z9 F720 ; Move print head up 
G1 X100 Y200 F3600 ; park 
G1 Z57 F720 ; Move print head further up 
G4 ; wait 
M221 S100 ; reset flow

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan 
M84 ; disable motors 
M73 P100 R0 
M73 Q100 S0

; filament used [mm] = 30
; filament used [cm3] = 0.05
; filament used [g] = 0.08
; filament cost = 0.01
; total filament used [g] = 0.08
; total filament cost = 0.01
; estimated printing time (normal mode) = 00m 17s
; estimated printing time (silent mode) = 00m 17s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.6
; external_perimeter_speed = 35
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.5
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.4
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Generic PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 230
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.5
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 85
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.3
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.5
; perimeter_generator = arachne
; perimeter_speed = 50
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.30mm DRAFT @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 30
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.5
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.11.0 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.38
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 45
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 230
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 8
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.45
; top_solid_infill_speed = 40
; top_solid_layers = 4
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end